"""empty message

Revision ID: 2fdd5b6129df
Revises: 9da7755157b9
Create Date: 2020-04-20 22:32:17.695184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdd5b6129df'
down_revision = '9da7755157b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helper_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helper_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Actor_id'], ['actor.id'], name='helper_table_Actor_id_fkey'),
    sa.ForeignKeyConstraint(['Movie_id'], ['movie.id'], name='helper_table_Movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='helper_table_pkey')
    )
    # ### end Alembic commands ###
