"""empty message

Revision ID: 5faeea6a0608
Revises: 9e416794a709
Create Date: 2020-04-20 21:02:12.666198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5faeea6a0608'
down_revision = '9e416794a709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('helper_table', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('helper_table', 'id')
    # ### end Alembic commands ###
