"""empty message

Revision ID: 9da7755157b9
Revises: 5faeea6a0608
Create Date: 2020-04-20 21:46:44.471589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da7755157b9'
down_revision = '5faeea6a0608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('helper_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helper_table',
    sa.Column('Actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Actor_id'], ['actor.id'], name='helper_table_Actor_id_fkey'),
    sa.ForeignKeyConstraint(['Movie_id'], ['movie.id'], name='helper_table_Movie_id_fkey'),
    sa.PrimaryKeyConstraint('Actor_id', 'Movie_id', name='helper_table_pkey')
    )
    # ### end Alembic commands ###
