"""empty message

Revision ID: 9e416794a709
Revises: 
Create Date: 2020-04-19 23:04:41.597747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e416794a709'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
